CREATE TABLE TOTAL_HABERES(
    ID_EMP NUMBER(6)
    , APELLIDO_EMP VARCHAR (22)
    , SUEL_ANT NUMBER(10)
    , SUEL_RECAL NUMBER(10)
    , BONO_DEP NUMBER (10)
    , DESC_LEGALES NUMBER (10)
    , TOTAL_HABERES NUMBER(10)
)