DECLARE


    V_NUEVO_SALARIO NUMBER;
    V_ID_EMPLEADO NUMBER :=105;
    
BEGIN
    V_NUEVO_SALARIO := PAQ_REAJUSTE_X_CAMBIO_DEPTO.FNC_CAL_SALARIO(V_ID_EMPLEADO, 10);
    
    PAQ_REAJUSTE_X_CAMBIO_DEPTO.SP_ACTUALIZA_SALARIO (V_ID_EMPLEADO, V_NUEVO_SALARIO);
    
    PAQ_REAJUSTE_X_CAMBIO_DEPTO.SP_CAMBIAR_DEPTO(V_ID_EMPLEADO, 70);



END;