CREATE OR REPLACE PACKAGE PAQ_REAJUSTE_X_CAMBIO_DEPTO AS
    
    FUNCTION FNC_CAL_SALARIO(EMP_ID IN NUMBER, AUMENTO_PCT IN NUMBER) RETURN NUMBER;
    
    PROCEDURE SP_ACTUALIZA_SALARIO(EMP_ID IN NUMBER, NUEVO_SALARIO IN NUMBER);
    
    PROCEDURE SP_CAMBIAR_DEPTO(EMP_ID IN NUMBER, NUEVO_DEPTO IN NUMBER);



END PAQ_REAJUSTE_X_CAMBIO_DEPTO;


CREATE OR REPLACE PACKAGE BODY PAQ_REAJUSTE_X_CAMBIO_DEPTO AS

    FUNCTION FNC_CAL_SALARIO(EMP_ID IN NUMBER,AUMENTO_PCT IN NUMBER) RETURN NUMBER IS
        V_SALARIO_ACTUAL NUMBER;
        V_NUEVO_SALARIO NUMBER;
    BEGIN
    
            SELECT SALARY INTO V_SALARIO_ACTUAL
            FROM EMPLEADOS
            WHERE EMPLOYEE_ID = EMP_ID;
            
            V_NUEVO_SALARIO := V_SALARIO_ACTUAL + (V_SALARIO_ACTUAL * AUMENTO_PCT/100);
            
            RETURN V_NUEVO_SALARIO;
    END FNC_CAL_SALARIO;
    PROCEDURE SP_ACTUALIZA_SALARIO(EMP_ID IN NUMBER, NUEVO_SALARIO IN NUMBER)IS
    BEGIN
        UPDATE EMPLEADOS 
        SET SALARY = NUEVO_SALARIO
        WHERE EMPLOYEE_ID = EMP_ID;
        COMMIT;
    END SP_ACTUALIZA_SALARIO;
    
    PROCEDURE SP_CAMBIAR_DEPTO(EMP_ID IN NUMBER, NUEVO_DEPTO IN NUMBER)IS
    BEGIN
            UPDATE EMPLEADOS
            SET DEPARTMENT_ID = NUEVO_DEPTO
            WHERE EMPLOYEE_ID = EMP_ID;
            COMMIT;
        END SP_CAMBIAR_DEPTO;
END PAQ_REAJUSTE_X_CAMBIO_DEPTO;
        
SELECT * FROM EMPLEADOS WHERE EMPLOYEE_ID = 105;


