/*

    CREE UNA FUNCION QUE, INGRESANDO EL ID DE UN DEPARTAMENTO, ME RETORNE LA CANTIDAD DE 
    EMPLEADOS QUE TRABAJAN EN EL DEPARTAMENTO INGRESADO
    
    CREE UNA FUNCION QUE INGRESANDO EL DATO EMPLOYEE_ID, RETORNE EL PAÍS EN EL QUE VIVE 
    EL EMPLEADO
    
    CREE UNA FUNCION QUE PERMITA INGRESAR EL ID DE UN EMPLEADO, Y QUE RETORNE EL NOMBRE DEL JEFE. 
    
*/


CREATE OR REPLACE FUNCTION CANT_EMPLEADOS(V_ID_DEPA NUMBER)
RETURN  NUMBER
IS 
    V_CANT_EMPLEADOS NUMBER;

BEGIN 

    SELECT COUNT(EMPLOYEE_ID)
    INTO V_CANT_EMPLEADOS
    FROM EMPLOYEES
    WHERE DEPARTMENT_ID = V_ID_DEPA;
    
    RETURN V_CANT_EMPLEADOS;
    
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        INSERT INTO ERROR_PROCESO VALUES(SYSDATE, 'CANT_EMPLEADOS', 'NO SE ENCONTRO EL DEPARTAMENTO');
    WHEN OTHERS THEN
        INSERT INTO ERROR_PROCESO VALUES(SYSDATE, 'CANT_EMPLEADOS', 'OTRO ERROR');
END;


-----------------------

/*CREE UNA FUNCION QUE INGRESANDO EL DATO EMPLOYEE_ID, RETORNE EL PAÍS EN EL QUE VIVE 
    EL EMPLEADO*/
    
CREATE OR REPLACE FUNCTION VER_PAIS(V_EMPLOYEE_ID NUMBER)
RETURN VARCHAR    
IS 
    V_NOMBRE_PAIS VARCHAR(100);
BEGIN 
    
    SELECT C.COUNTRY_NAME
    INTO V_NOMBRE_PAIS
    FROM COUNTRIES C
    RIGHT JOIN LOCATIONS L ON C.COUNTRY_ID = L.COUNTRY_ID
    RIGHT JOIN DEPARTMENTS D ON D.LOCATION_ID = L.LOCATION_ID
    RIGHT JOIN EMPLOYEES E ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
    WHERE E.EMPLOYEE_ID = V_EMPLOYEE_ID;
    
    RETURN V_NOMBRE_PAIS;


END;
    
    
/*
CREE UNA FUNCION QUE PERMITA INGRESAR EL ID DE UN EMPLEADO, Y QUE RETORNE EL NOMBRE DEL JEFE. 
*/    
    
CREATE OR REPLACE FUNCTION  MANAGER_NAME(V_EMPLOYEE_ID NUMBER)
RETURN VARCHAR    
IS

    V_NOMBRE_JEFE VARCHAR(100);
BEGIN 

    SELECT JEFES.FIRST_NAME
    INTO V_NOMBRE_JEFE
    FROM EMPLOYEES EMP
    JOIN EMPLOYEES JEFES ON  EMP.MANAGER_ID = JEFES.EMPLOYEE_ID
    WHERE EMP.EMPLOYEE_ID = V_EMPLOYEE_ID;
    
    RETURN V_NOMBRE_JEFE;

END;


    


    
    
    
    
    
    
    
    
    
    
    
    

        


