DECLARE
    V_CODIGO_ERROR NUMBER;
    V_DESC_ERROR VARCHAR(250);
    
    INSERT_NULL EXCEPTION;
    PRAGMA EXCEPTION_INIT(ISERT_NULL,-01400);

BEGIN
    insert into DEPARTMENTS VALUES(300,NULL, 200,1700);
    
EXCEPTION

    WHEN DUP_VAL_ON_INDEX THEN
    INSERT INTO ERROR_PROCESO VALUES
        INSERT INTO ERROR_PROCESO VALUES(SYSDATE,'BLOQUE ANONIMO DE INSERCION DE DEPARTAMENTO NUEVO'
        , ' ERROR AL INTENTAR INSERTAT LA PRIMARY KEY DUPLICADA');
    WHEN INSERT_NULL THEN

        INSERT INTO ERROR_PROCESO VALUES
        (SYSDATE,
        'BLOQUE ANONIMO DE INSERCION DE DEPARTAMENTO NUEVO'
        ,'SE INTENTO INSERTAR DATOS NULLOS EN LA COLUMNA DEFINIDA COMO NOT NULL');
end;

SELECT * FROM 

