
 -- mi primer bloque
-- DECLARE -- OPCIONAL
-- BEGIN
-- END;


-- SET SERVEROUTPUT ON;
VARIABLE v_bind number
exec :v_bind := 7990;
 DECLARE
 V_NOMBRE VARCHAR2(50);
 V_SUELDO NUMBER;
 V_EDAD NUMBER;
 V_PORCENTAJEAU NUMBER := 0.15;
 V_NUEVOSUELDO NUMBER:=0;
 v_idempleado number := &ingreseIDEMP;
 v_cargo  employees.job_id%TYPE;
 v_comision number;
 V_PCOMI NUMBER := 0.02;
 BEGIN
 SELECT FIRST_NAME || ' ' || LAST_NAME
 ,SALARY
 ,TRUNC(MONTHS_BETWEEN(SYSDATE,HIRE_DATE)/12)
 ,job_id
 INTO V_NOMBRE,V_SUELDO,V_EDAD, V_CARGO
 FROM EMPLOYEES
 WHERE EMPLOYEE_ID = v_idempleado;
 
 V_NUEVOSUELDO := V_SUELDO + (V_SUELDO * V_PORCENTAJEAU);
 -- CALCULO DE LA COMISION
 V_COMISION := v_nuevosueldo * V_PCOMI;

 DBMS_OUTPUT.PUT_LINE('NOMBRE: '|| V_NOMBRE);
 DBMS_OUTPUT.PUT_LINE('SUELDO ANTIGUO: '|| V_SUELDO);
DBMS_OUTPUT.PUT_LINE('AÑOS DE SERVICIO: '|| V_EDAD || ' AÑOS');
 DBMS_OUTPUT.PUT_LINE('SUELDO AUMENTADO: '|| V_NUEVOSUELDO);
 DBMS_OUTPUT.PUT_LINE('CARGO OCUPADO: '|| V_CARGO);
 DBMS_OUTPUT.PUT_LINE('COMISION: '|| ROUND(V_COMISION));
DBMS_OUTPUT.PUT_LINE('Variable de enlace parametro: '|| :v_bind);

 END;
