/* Creación de usuario si está trabajando con BD Oracle XE */
CREATE USER MDY2131_P8 IDENTIFIED BY "MDY2131.practica_8"
DEFAULT TABLESPACE "USERS"
TEMPORARY TABLESPACE "TEMP";
ALTER USER MDY2131_P8 QUOTA UNLIMITED ON USERS;
GRANT CREATE SESSION TO MDY2131_P8;
GRANT "RESOURCE" TO MDY2131_P8;
ALTER USER MDY2131_P8 DEFAULT ROLE "RESOURCE";

/* Creación de usuario si está trabajando con BD Oracle Cloud */
CREATE USER MDY2131_P8 IDENTIFIED BY "MDY2131.practica_8"
DEFAULT TABLESPACE "DATA"
TEMPORARY TABLESPACE "TEMP";
ALTER USER MDY2131_P8 QUOTA UNLIMITED ON DATA;
GRANT CREATE SESSION TO MDY2131_P8;
GRANT "RESOURCE" TO MDY2131_P8;
ALTER USER MDY2131_P8 DEFAULT ROLE "RESOURCE"